# ${project.artifactId} v${project.version}
server-main = "prison"
server-queue = "hub"
name = "OPGods.net" # ;)
max-players = 710
message-position = "Position in queue: "
message-connecting = "Connecting to the server..."
message-full = "Server is currently full!"
message-offline = "Server is currently down!"
kick = true
wait-on-kick = 16
send-title = true
title-message = "&6Queue Status"
subtitle-message = "&ePosition: %position%/%total%" # I ended up changing this in the code, so it just says whatever message-offline says, easy fix if you wanna revert it back in src
